# Generated by Django 5.1.3 on 2025-10-03 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=20)),
                ('Apellido', models.CharField(max_length=20)),
                ('Numero_telefono', models.CharField(max_length=15)),
                ('Direccion', models.CharField(max_length=50)),
                ('Rut', models.IntegerField()),
                ('Activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Marca', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Modelo', models.CharField(max_length=50)),
                ('Marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Modelos.marca')),
            ],
        ),
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=30)),
                ('Trabajo_realizado', models.CharField(max_length=100)),
                ('Codigo_Bloqueo', models.CharField(max_length=50)),
                ('Activo', models.BooleanField(default=True)),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Modelos.modelo')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('N_Orden', models.AutoField(primary_key=True, serialize=False)),
                ('Fecha', models.CharField(max_length=30)),
                ('Coste', models.IntegerField()),
                ('Abono', models.IntegerField()),
                ('Restante', models.IntegerField()),
                ('Activo', models.BooleanField(default=True)),
                ('Cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Modelos.cliente')),
                ('Dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Modelos.dispositivo')),
            ],
        ),
    ]
