# Generated by Django 5.1.3 on 2025-11-07 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Origen', models.CharField(choices=[('NAC', 'Nacional'), ('EXT', 'Extranjero')], default='NAC', max_length=3)),
                ('Nombre', models.CharField(max_length=20)),
                ('Apellido', models.CharField(max_length=20)),
                ('Numero_telefono', models.CharField(max_length=15, null=True)),
                ('Rut', models.CharField(max_length=50)),
                ('Activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Marca', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Falla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Falla', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Modelo', models.CharField(max_length=50)),
                ('Marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modelos', to='Base_Datos.marca')),
            ],
            options={
                'verbose_name_plural': 'Modelos',
            },
        ),
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Activo', models.BooleanField(default=True)),
                ('Metodo_Bloqueo', models.CharField(choices=[('PIN', 'PIN'), ('PASS', 'Contraseña'), ('PATRON', 'Patrón (matriz 3x3)')], default='PASS', max_length=6)),
                ('Codigo_Bloqueo', models.CharField(max_length=50)),
                ('rut', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispositivos', to='Base_Datos.cliente')),
                ('modelo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispositivos', to='Base_Datos.modelo')),
            ],
            options={
                'verbose_name_plural': 'Dispositivos',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('N_Orden', models.AutoField(primary_key=True, serialize=False)),
                ('Fecha', models.DateField()),
                ('Coste', models.IntegerField()),
                ('Abono', models.IntegerField()),
                ('Restante', models.IntegerField()),
                ('Activo', models.BooleanField(default=True)),
                ('Estado', models.CharField(choices=[('REG', 'Registrado'), ('PRO', 'En proceso'), ('TER', 'Terminado')], default='REG', max_length=3)),
                ('Observaciones', models.CharField(max_length=50, null=True)),
                ('Dispositivo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to='Base_Datos.dispositivo')),
                ('Tipo_de_falla', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to='Base_Datos.tipo_falla')),
            ],
            options={
                'verbose_name_plural': 'Pedidos',
            },
        ),
    ]
