# Generated by Django 5.2.5 on 2025-11-03 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_Datos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reparacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('numero_orden', models.CharField(max_length=20)),
                ('fecha_ingreso', models.DateField()),
                ('rut', models.CharField(max_length=12)),
                ('marca', models.CharField(max_length=50)),
                ('equipo', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('pendiente', 'Pendiente'), ('entregado', 'Entregado')], max_length=50)),
            ],
        ),
    ]
