# Generated by Django 5.2.5 on 2025-11-13 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_Datos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={},
        ),
        migrations.AddField(
            model_name='cliente',
            name='DocumentoExtranjero',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='Rut',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
