# Generated by Django 5.2.5 on 2025-11-06 00:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_Datos', '0002_reparacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispositivo',
            name='Nombre',
        ),
        migrations.RemoveField(
            model_name='dispositivo',
            name='Trabajo_realizado',
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='Marca',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Base_Datos.marca'),
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='Tipo_de_falla',
            field=models.CharField(choices=[('pantalla_rota', 'Pantalla rota'), ('mojado', 'Celular mojado'), ('no_enciende', 'No enciende'), ('carga', 'Problemas de carga'), ('audio', 'Fallas de audio'), ('senal', 'Problemas de señal'), ('otros', 'Otros')], default='otros', max_length=50),
        ),
    ]
