# Generated by Django 5.2.5 on 2025-11-13 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_Datos', '0002_alter_cliente_options_cliente_documentoextranjero_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='Numero_telefono',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
