# Generated by Django 5.2.5 on 2025-11-06 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_Datos', '0003_remove_dispositivo_nombre_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='dispositivo',
            options={'verbose_name_plural': 'Dispositivos'},
        ),
        migrations.AlterModelOptions(
            name='marca',
            options={'verbose_name_plural': 'Marcas'},
        ),
        migrations.AlterModelOptions(
            name='modelo',
            options={'verbose_name_plural': 'Modelos'},
        ),
        migrations.AlterModelOptions(
            name='pedido',
            options={'verbose_name_plural': 'Pedidos'},
        ),
        migrations.AlterModelOptions(
            name='reparacion',
            options={'verbose_name_plural': 'Reparaciones'},
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='Tipo_de_reparacion',
            field=models.CharField(choices=[('hardware', 'Hardware'), ('software', 'Software'), ('diagnostico', 'Diagnóstico'), ('mantenimiento', 'Mantenimiento'), ('otros', 'Otros')], default='otros', max_length=50),
        ),
    ]
