# Generated by Django 5.2.5 on 2025-11-15 17:48

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_Datos', '0003_alter_cliente_numero_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispositivo',
            name='Codigo_Bloqueo',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='Abono',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='Coste',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='Observaciones',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='Restante',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AddConstraint(
            model_name='marca',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('Marca'), name='unique_marca_ci'),
        ),
        migrations.AddConstraint(
            model_name='modelo',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('Modelo'), models.F('Marca'), name='unique_modelo_por_marca_ci'),
        ),
    ]
