# Generated by Django 5.2.5 on 2025-11-06 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_Datos', '0004_alter_cliente_options_alter_dispositivo_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoFalla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Tipos de falla',
            },
        ),
        migrations.CreateModel(
            name='TipoReparacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Tipos de reparación',
            },
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='Marca',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dispositivos', to='Base_Datos.marca'),
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='modelo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispositivos', to='Base_Datos.modelo'),
        ),
        migrations.AlterField(
            model_name='modelo',
            name='Marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modelos', to='Base_Datos.marca'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='Cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='Base_Datos.cliente'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='Dispositivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='Base_Datos.dispositivo'),
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='Tipo_de_falla',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispositivos', to='Base_Datos.tipofalla'),
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='Tipo_de_reparacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispositivos', to='Base_Datos.tiporeparacion'),
        ),
    ]
