# Generated by Django 5.2.5 on 2025-11-22 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_Datos', '0004_alter_dispositivo_codigo_bloqueo_alter_pedido_abono_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='Observaciones',
            field=models.TextField(blank=True, null=True),
        ),
    ]
