# Generated by Django 5.2.5 on 2025-11-06 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_Datos', '0005_tipofalla_tiporeparacion_alter_dispositivo_marca_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispositivo',
            name='Tipo_de_reparacion',
        ),
        migrations.AlterModelOptions(
            name='marca',
            options={},
        ),
        migrations.AlterField(
            model_name='marca',
            name='Marca',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='TipoReparacion',
        ),
    ]
