# Generated by Django 5.1.3 on 2025-11-06 23:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_Datos', '0006_remove_dispositivo_tipo_de_reparacion_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reparacion',
        ),
        migrations.RemoveField(
            model_name='dispositivo',
            name='Tipo_de_falla',
        ),
        migrations.RemoveField(
            model_name='dispositivo',
            name='Marca',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='Cliente',
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='rut',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispositivos', to='Base_Datos.cliente'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='Estado',
            field=models.CharField(choices=[('REG', 'Registrado'), ('PRO', 'En proceso'), ('TER', 'Terminado')], default='REG', max_length=3),
        ),
        migrations.AddField(
            model_name='pedido',
            name='Tipo_de_falla',
            field=models.CharField(default='prueba', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pedido',
            name='Dispositivo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to='Base_Datos.dispositivo'),
        ),
        migrations.DeleteModel(
            name='TipoFalla',
        ),
    ]
