# Generated by Django 5.1.3 on 2025-11-07 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_Datos', '0007_delete_reparacion_remove_dispositivo_tipo_de_falla_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='Fecha',
            field=models.DateField(),
        ),
    ]
